f() {
  try {
    m()<spot></spot>
  } on Exception catch (e, s) {
    print(s);
  }
}
